paulirwin/JavaToCSharp

- JavaToCSharp/Expressions/DoubleLiteralExpressionVisitor.cs
Nordic locale wants to use float/double numbers in format "0,00" by default. Which of course does not work very well with the java/c# syntax. Force the default locale to always use dot instead.
> Correctly parse float/double even with nordic locale

- JavaToCSharp.Tests/ConvertTypeTests.cs
- JavaToCSharp.Tests/JavaToCSharp.Tests.csproj
- JavaToCSharp.sln
Fixes #13 
- Added a _Tests_ solution folder and a xUnit test project named _JavaToCSharp.Tests_
- Added `ConvertTypeTests` with 1 failing test [`ConvertType_IntArray_BracketsAfterType()`](https://github.com/paulirwin/JavaToCSharp/pull/14/files#diff-9d93d02796cb5de8c744619a3ea65d4d31afa16ac33c368c1bc3ede25b29423dR25) to demonstrate the issue in #11. I plan to submit separate PR for that issue which will also fix the failing test.
- Improves the development experience by having tests
- No
- Minimal
- Ran the newly added tests in the Test Explorer
- Ran the newly added tests using `dotnet test` from the command line
> Add xUnit test project and ConvertTypeTests

- JavaToCSharp.Tests/ConvertTypeTests.cs
- JavaToCSharp/TypeNameParser.cs
Fixes #11 
- Fix the type name parser tokenize pattern to also match on left and right square brackets so that array square bracket pairs may be preserved during conversion.
- Array square bracket pairs will now be preserved during conversion.
- No
- Could break people who expect the array square brackets to get dropped but this is unlikely and not something that should be considered breaking.
- Ran unit tests and the previously failing test `ConvertType_IntArray_BracketsAfterType()` is now passing.
> Preserve array square bracket pairs when parsing type names

- JavaToCSharp/TypeHelper.cs
- `Long/Float` Type-Name conversion is supported
- fix: [RuoYi-common-model-LoginUser-Long-Type-Field]( https://github.com/yangzongzhuan/RuoYi-Vue/blob/324342800985a3e543a6ce308daeb219bdfbada0/ruoyi-common/src/main/java/com/ruoyi/common/core/domain/model/LoginUser.java#L22)
- Add `decimal` keyword in `EscapeIdentifier`
- fix: [RuoYi-common-utils-HTMLFilter-name-decimal-method-parameter](https://github.com/yangzongzhuan/RuoYi-Vue/blob/7479ff4b06680cb7cca3a9cd987c4d6efb2d0032/ruoyi-common/src/main/java/com/ruoyi/common/utils/html/HTMLFilter.java#L175)
> Added escape of some keywords that `TypeHelper` missed

- JavaToCSharp/TypeHelper.cs
- fix useless calls to `ExpressionVisitor.VisitExpression()` in `TypeHelper.TryTransformMethodCall` implementations.
- Long `Fluent method` calls trigger `loop nested calls`
```java
package com.ruoyi.framework.config;
public class SecurityConfig
{
@Override
protected void configure(HttpSecurity httpSecurity) throws Exception
{
httpSecurity
.csrf().disable()
.exceptionHandling().authenticationEntryPoint(unauthorizedHandler).and()
.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS).and()
.authorizeRequests()
.antMatchers("/login", "/register", "/captchaImage").anonymous()
.antMatchers(
HttpMethod.GET,
"/",
"/*.html",
"/**/*.html",
"/**/*.css",
"/**/*.js",
"/profile/**"
).permitAll()
.antMatchers("/swagger-ui.html").anonymous() …
```
> fix `loop nested calls` to `VisitExpression` in `TypeHelper.TryTransformMethodCall`

- JavaToCSharpCli/JavaToCSharpCli.csproj
- JavaToCSharpCli/Program.cs
- JavaToCSharpCli/log4net.config
- Support folder to folder converting. 
- Enhance error handling to prevent any exception interrupting from folder convert going. 
- Adopt **_log4net_** for logging to replace **_Console.WriteLine_**.
Anyway, you guys' work really help me lots.
> Some feature functions for CLI.

- JavaToCSharp.Tests/VisitLiteralExpressionTests.cs
- JavaToCSharp/Expressions/CharLiteralExpressionVisitor.cs
- JavaToCSharp/Expressions/StringLiteralExpressionVisitor.cs
Fixes #20 and correctly parses escaped characters in a char literal.
`'\n'` would get translated to `'\\'` which is not correct.
Also includes some tests for the two fixes.
> Fix string and char literal expression parsing

- JavaToCSharp.Tests/ConvertInterfaceTests.cs
- JavaToCSharp/Declarations/ClassOrInterfaceDeclarationVisitor.cs
Currently interface extends are not converted to their C# equivalent. This PR fixes it.
> Convert interface extends

- JavaToCSharp.Tests/IntegrationTests.cs
- JavaToCSharp.Tests/Resources/Java9DiamondOperatorInnerClass.java
This adds a unit test for the Java 9 diamond operator in inner classes syntax. It does not successfully build and run so for now this is a conversion test only. Anonymous types currently require a bit of manual clean-up after converted usually anyways. Maybe there's a way we could better do this, but things like `<? extends Number>` might be more difficult.
> Java 9 Diamond Inner Class Test

- JavaToCSharp.Tests/ConvertInterfaceTests.cs
- JavaToCSharp.Tests/IntegrationTests.cs
- JavaToCSharp.Tests/Resources/Java9PrivateInterfaceMethods.java
- JavaToCSharp/Declarations/ClassOrInterfaceDeclarationVisitor.cs
- JavaToCSharp/Declarations/ConstructorDeclarationVisitor.cs
- JavaToCSharp/Declarations/EnumDeclarationVisitor.cs
- JavaToCSharp/Declarations/FieldDeclarationVisitor.cs
- JavaToCSharp/Declarations/MethodDeclarationVisitor.cs
- JavaToCSharp/Extensions.cs
This converts interface methods with a body, such as default and private interface methods, to C# 8 interface methods with bodies.
Also, this cleans up some use of modifier keyword determination that was messy as a reult of the JavaParser upgrade.
> Transformer: Support converting default/private interface methods, #53

- JavaToCSharp.Tests/IntegrationTests.cs
- JavaToCSharp.Tests/Resources/Java10TypeInference.java
This was already accidentally supported, but now we're making our support for type inference explicit and under test.
> Tests: Add test for Java 10 type inference, #53

- JavaToCSharp.Tests/IntegrationTests.cs
- JavaToCSharp.Tests/Resources/Java11LambdaInference.java
Just like regular type inference for Java 10, we already accidentally supported this since `var` is the same in both languages. In this case, we cannot make this a full integration test due to some issues noted in the test file comments.
> Tests: Add parse test for Java 11 lambda parameter type inference, #53

- JavaToCSharp.Tests/IntegrationTests.cs
- JavaToCSharp.Tests/Resources/NewArrayLiteralBug.java
- JavaToCSharp/Expressions/ArrayCreationExpressionVisitor.cs
Fixes generated C# for array creation expressions. Was (incorrectly) i.e. `new float { ... }` when it should be `new float[] { ... }`
> Fix issue with array creation expressions, #38

- JavaToCSharpGui/ViewModels/MainWindowViewModel.cs
Fixes a small non-test friendly bit of code that slipped through, which depends on a static class, instead of an interface.
Fixes #71
> fix: use dispatcher interface, not the static class

- JavaToCSharpCli/JavaToCSharpCli.csproj
- JavaToCSharpCli/Program.cs
Resolves #58 except for package translations. Might add that in the future maybe with an i.e. `--replace-package=com.whatever.foo/Whatever.Foo` syntax? But that day is not today.
> Support (almost) all options in the CLI app, #58

- JavaToCSharpGui/Infrastructure/HostStorageProvider.cs
- JavaToCSharpGui/Infrastructure/IHostStorageProvider.cs
- JavaToCSharpGui/ViewModels/MainWindowViewModel.cs
- JavaToCSharpGui/Views/MainWindow.axaml
Adds a save button to the GUI.
> GUI: Add save button, #109

- JavaToCSharp/CommentsHelper.cs
- JavaToCSharp/Declarations/ConstructorDeclarationVisitor.cs
- JavaToCSharp/Extensions.cs
- JavaToCSharp/JavaConversionOptions.cs
- JavaToCSharp/JavaToCSharpConverter.cs
- JavaToCSharp/UsingsHelper.cs
- JavaToCSharp/Whitespace.cs
- JavaToCSharpCli/Program.cs
- JavaToCSharpGui/App.config
- JavaToCSharpGui/CurrentOptions.cs
- JavaToCSharpGui/Properties/Settings.Designer.cs
- JavaToCSharpGui/Properties/Settings.settings
- JavaToCSharpGui/ViewModels/SettingsWindowViewModel.cs
- JavaToCSharpGui/Views/SettingsWindow.axaml
This change surfaced some annoying whitespace behavior with Roslyn's NormalizeWhitespace method, so this adds some leading/trailing newlines in places after NormalizeWhitespace is called to help prettify the output.
> Add support for file-scoped namespaces, #113

- JavaToCSharp.Tests/ConvertExpressionTests.cs
- JavaToCSharp/Expressions/FieldAccessExpressionVisitor.cs
- JavaToCSharp/TypeHelper.cs
Fixes #119 
- Converts string length expressions `str.length()` into `str.Length`
- Converts array length expressions `arr.length` into `arr.Length`
- Adds tests for similar conversions already implemented (size, get, set)
> Convert array and string length into a property accessor

- JavaToCSharp/JavaConversionOptions.cs
- JavaToCSharpCli/Program.cs
Closes #122 Added a new CLI option `--include-subdirectories` applicable when de `dir` command is specified:
- if true (default): preserves the current behaviour (converts the sources in the directory and all its subdirectories)
- if false: only converts the sources in the directory, excluding subdirectories
> Option to convert files excluding subdirectories

- JavaToCSharp.Tests/SyntaxMappingTests.cs
- JavaToCSharp/Declarations/MethodDeclarationVisitor.cs
- JavaToCSharp/Expressions/MethodCallExpressionVisitor.cs
- JavaToCSharp/JavaConversionOptions.cs
- JavaToCSharp/JavaToCSharp.csproj
- JavaToCSharp/SyntaxMapping.cs
- JavaToCSharp/UsingsHelper.cs
- JavaToCSharpCli/Program.cs
- README.md
This PR Closes #118 to enable the conversion of JUnit tests. This is done by converting the test annotations, imports and assert methods using a collection of mappings that are read from an optional external file.
The submitted PR includes two commits (please, tell me if you prefer to submit it as two separate sequential PRs):
1) **Read mappings file** (463d247cf5aa3d522297f76bcaee47451158ec23): 
A new optional CLI option `--mappings-file` specifies the mappings file for imports, annotations and methods (either void or non void). Example:
```
ImportMappings:
org.junit.Test : Xunit
org.junit.Assert.assertEquals : ""
org.junit.Assert.assertTrue : ""
VoidMethodMappings:
assertEquals : Assert.Equal
assertTrue : Assert.True
AnnotationMappings:
Test : Fact
```
2) **Apply mappings during the …
> Add mappings from imports, methods and annotations to support JUnit test conversions

- JavaToCSharp.Tests/CommentTests.cs
- JavaToCSharp/CommentsHelper.cs
Fixes #88, Fixes #131. See the discussion in this issue for the rationale of this fix.
> Avoid repeated comments in subclasses and interface implementations

- JavaToCSharp.Tests/CommentTests.cs
- JavaToCSharp.Tests/ConvertTypeTests.cs
- JavaToCSharp/Declarations/ClassOrInterfaceDeclarationVisitor.cs
- JavaToCSharp/TypeHelper.cs
This PR closes #125 by converting java bounded type parameters in class declarations into C# generic type constraints.
Draft will be ready after merge #126, rebase, and fix comment tests
> Convert class bounded type parameters
